env:
  TERM: xterm-256color

window:
  padding:
    x: 10
    y: 10

  dimensions:
    columns: 80
    lines: 24

font:
  normal:
    family: Iosevka Term
    style: Light Extended 

  bold:
    family: Iosevka Term
    style: Medium Extended
  
  italic:
    family: Iosevka Term
    style: Light Extended Italic

  bold_italic:
    family: Iosevka Term
    style: Medium Extended Italic

  size: 10.0

colors:

  primary:
    background: '#0f1117'
    foreground: '#fbf1c7'

  normal:
    bg:      '#0f1117'
    red:     '#cc241d'
    green:   '#98971a'
    yellow:  '#d79921'
    blue:    '#458588'
    purple:  '#b16286'
    aqua:    '#689d6a'
    gray:    '#a89984'
    
  bright: 
    gray:    '#928374'
    red:     '#fb4934'
    green:   '#b8bb26'
    yellow:  '#fabd2f'
    blue:    '#83a598'
    purple:  '#d3869b'
    aqua:    '#8ec07c'
    fg:      '#fbf1c7'

